name:                users-microservice
version:             0.1.0.0
github:              "hq9907/users-microservice"
license:             BSD3
author:              "Qiao Huang"
maintainer:          "qh2234@columbia.edu"
copyright:           "2022 Qiao Huang"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            A simple microservice to manage users
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/hq9907/users-microservice#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- text
- mtl
- bytestring
- monad-logger
- transformers
- resourcet
- persistent
- persistent-mysql
- servant
- servant-server
- servant-options
- wai
- wai-cors
- warp

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  users-microservice-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - users-microservice

tests:
  users-microservice-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - users-microservice
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
    - aeson-qq
